version: '3.9'

services:
  al-db:
    image: mongo
    env_file:
      - .env
    restart: always
    ports:
      - "27017:27017"

  al-back:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    environment:
      DEBUG: 1
    volumes:
      - .:/code
    depends_on:
      - al-db
    ports:
      - "5000:5000"